# Generated by Django 3.2 on 2025-02-06 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id_department', models.AutoField(primary_key=True, serialize=False)),
                ('name_dep', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_file', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('id_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('name_user', models.CharField(max_length=50)),
                ('mail_user', models.EmailField(max_length=50, unique=True)),
                ('psw_user', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=100)),
                ('id_dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.department')),
            ],
        ),
        migrations.DeleteModel(
            name='Utilisateur',
        ),
        migrations.AddField(
            model_name='files',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.user'),
        ),
    ]
